apiVersion: v2
name: raster-catalog-manager
description: A Helm chart for raster-catalog-manager service
type: application
version: 7.0.0
appVersion: 7.0.0

dependencies:
  - name: mclabels
    version: 1.0.1
    repository: oci://acrarolibotnonprod.azurecr.io/helm/infra
